name: Archibus-Automated-Scheduler

on:
    workflow_dispatch:
    schedule:
      - cron: "0 9 * * 1,3,5"  # Runs at 9:00 AM UTC on Monday, Wednesday, and Friday
    
jobs:
  archibus-automated-scheduler:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.X

    - name: Install Chrome Browser
      run: |
        sudo apt-get update
        sudo apt-get install -y google-chrome-stable

          # Step 4: Install ChromeDriver

    - name: Install ChromeDriver
      run: |
        CHROME_VERSION=$(google-chrome --version | grep -oP '\d+\.\d+\.\d+')
        sudo apt-get install -y chromium-chromedriver
        sudo ln -s /usr/lib/chromium-browser/chromedriver /usr/local/bin/chromedriver

    - name: Install dependencies
      run: python -m pip install -r requirements.txt

    - name: python-archibus-scheduler
      run: |
        python src/main.py ${{ secrets.archibus_scheduling_args }}
